<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { useRoute, useRouter } from 'vue-router'
import { api } from '@/api/client'
import type { Artist, YouTubeCoverVideo } from '@/api/types'
import AppModal from '@/components/AppModal.vue'
import PageHeader from '@/components/PageHeader.vue'
const route=useRoute(); const router=useRouter(); const tab=ref<'list'|'search'>('list'); const mode=ref<'all'|'collab'>('all'); const search=ref(''); const peopleOpen=ref(false); const selectedPeople=ref<YouTubeCoverVideo['collaborators']>([])
const artistId=computed(()=>Number(route.params.artistId)||null); const collaboratorId=computed(()=>Number(route.query.collaborator)||null)
const artistsQ=useQuery({queryKey:['artists'],queryFn:api.artists.list}); const coversQ=useQuery({queryKey:computed(()=>['covers',artistId.value,collaboratorId.value]),queryFn:()=>api.youtubeCovers.list(artistId.value??undefined, collaboratorId.value??undefined)})
const agencies=['RK Music','KAMITSUBAKI STUDIO','RIOT MUSIC']; const agency=ref(agencies[0]); const artists=computed(()=> (artistsQ.data.value??[]).filter(a=>a.agency===agency.value)); const current=computed(()=> (artistsQ.data.value??[]).find(a=>a.id===artistId.value)); const covers=computed(()=> (coversQ.data.value??[]).filter(c=>(mode.value==='all'||c.collaborators.length)&&(!search.value||`${c.video_title} ${c.artist_name}`.toLowerCase().includes(search.value.toLowerCase()))));
function avatar(a:Artist){const source=a.sources.find(s=>s.source_type==='x'); const handle=source?.value.replace(/^@/,''); return a.spotify_image_url||(handle?`https://unavatar.io/x/${encodeURIComponent(handle)}`:'')} function openArtist(a:Artist){router.push(`/youtube-covers/artists/${a.id}`); tab.value='list'} function thumb(c:YouTubeCoverVideo){return `https://i.ytimg.com/vi/${c.youtube_video_id}/hqdefault.jpg`} function people(c:YouTubeCoverVideo){selectedPeople.value=c.collaborators;peopleOpen.value=true} function choose(p:{id:number}){peopleOpen.value=false;router.push({query:{collaborator:p.id}})} function clear(){router.push(`/youtube-covers/artists/${artistId.value}`)}
</script>
<template><div class="page"><PageHeader eyebrow="YOUTUBE ARCHIVE / COVERS" title="YouTube 커버곡" description="공식 채널의 커버 영상과 함께 부른 아티스트를 확인합니다."/><div class="nav-pills"><UButton class="button" :class="{active:tab==='list'}" @click="tab='list'">리스트</UButton><UButton class="button" :class="{active:tab==='search'}" @click="tab='search'">검색</UButton></div><template v-if="tab==='list'&&!artistId"><div class="agency-pills"><UButton v-for="x in agencies" :key="x" class="button" :class="{active:agency===x}" @click="agency=x">{{x}}</UButton></div><div class="artist-grid"><button v-for="a in artists" :key="a.id" class="artist-card" @click="openArtist(a)"><img v-if="avatar(a)" :src="avatar(a)" :alt="a.name"><b v-else>{{a.name.slice(0,1)}}</b><span>{{a.display_name||a.name}}</span></button></div></template><template v-else><div class="cover-tools"><UButton class="button" @click="router.push('/youtube-covers')">아티스트 목록</UButton><template v-if="current"><strong>{{current.display_name||current.name}}</strong><UButton class="button" :class="{active:mode==='all'}" @click="mode='all'">전체</UButton><UButton class="button" :class="{active:mode==='collab'}" @click="mode='collab'">콜라보</UButton><UButton v-if="collaboratorId" class="button" @click="clear">참여자 필터 해제</UButton></template><UInput v-model="search" :placeholder="tab==='search'?'노래 제목 또는 가수 이름 검색':'이 아티스트의 커버 검색'"/></div><div v-if="coversQ.isPending.value" class="skeleton-list"><i/><i/><i/></div><div v-else class="cover-grid"><article v-for="c in covers" :key="c.id" class="cover-card"><a :href="c.youtube_url" target="_blank"><img :src="thumb(c)" :alt="c.video_title"></a><div><span>{{c.artist_name}}</span><h2>{{c.video_title}}</h2><UButton v-if="c.collaborators.length" class="button" @click="people(c)">콜라보 {{c.collaborators.length}}명</UButton></div></article></div><div v-if="!coversQ.isPending.value&&!covers.length" class="empty-state"><strong>표시할 커버곡이 없습니다.</strong></div></template><AppModal :open="peopleOpen" title="콜라보 참여 아티스트" description="선택하면 두 아티스트가 함께한 커버곡만 봅니다." @close="peopleOpen=false"><div class="people-list"><UButton v-for="p in selectedPeople" :key="p.id" class="button" @click="choose(p)">{{p.name}}</UButton></div></AppModal></div></template>
<style scoped>.nav-pills{display:flex;gap:8px;margin:0 0 14px}.nav-pills button{min-height:42px;padding:0 18px;border:1px solid var(--line);color:#8fa0b5;background:rgba(255,255,255,.02)}.nav-pills button.active{color:#061a10;border-color:#4de6a8;background:#4de6a8}.agency-pills,.cover-tools,.people-list{display:flex;gap:.6rem;flex-wrap:wrap;margin:1.2rem 0}.agency-pills{margin-top:0}.agency-pills button{min-height:42px;padding:0 18px;border:1px solid var(--line);border-radius:999px;color:#8fa0b5;background:rgba(255,255,255,.02)}.agency-pills button.active{color:#061a10;border-color:#4de6a8;background:#4de6a8}.artist-grid{display:grid;grid-auto-flow:row;grid-auto-columns:auto;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:1rem;overflow:visible;padding-bottom:0}.artist-card,.cover-card{border:1px solid var(--line);background:var(--panel);color:inherit;padding:.75rem}.artist-card{min-height:190px}.artist-card img{width:82px;height:82px;border-radius:50%;object-fit:cover}.artist-card span{display:block;margin-top:.5rem}.cover-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:1rem}.cover-card{padding:0}.cover-card img{width:100%;aspect-ratio:16/9;object-fit:cover}.cover-card div{padding:.8rem}.cover-card h2{font-size:1rem}@media(max-width:700px){.artist-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
