-- Runtime state for collection and Discord delivery. 001_initial.sql is immutable.

CREATE TABLE public.discord_users (
  discord_user_id TEXT PRIMARY KEY CHECK (discord_user_id ~ '^[0-9]+$'),
  display_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE public.discord_guilds (
  guild_id TEXT PRIMARY KEY CHECK (guild_id ~ '^[0-9]+$'),
  owner_discord_user_id TEXT REFERENCES public.discord_users(discord_user_id) ON DELETE RESTRICT,
  name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE public.discord_channels (
  channel_id TEXT PRIMARY KEY CHECK (channel_id ~ '^[0-9]+$'),
  guild_id TEXT NOT NULL REFERENCES public.discord_guilds(guild_id) ON DELETE RESTRICT,
  name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (guild_id, channel_id)
);

CREATE TABLE public.collection_states (
  external_account_id INTEGER PRIMARY KEY REFERENCES public.external_accounts(id) ON DELETE RESTRICT,
  cursor_value TEXT,
  last_seen_external_id TEXT,
  status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','polling','backoff','disabled','error')),
  consecutive_failures INTEGER NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
  next_poll_at TIMESTAMPTZ,
  lease_owner TEXT,
  lease_expires_at TIMESTAMPTZ,
  last_polled_at TIMESTAMPTZ,
  last_error TEXT,
  provider_state JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(provider_state) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL))
);

CREATE TABLE public.source_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_account_id INTEGER NOT NULL REFERENCES public.external_accounts(id) ON DELETE RESTRICT,
  external_id TEXT NOT NULL CHECK (length(btrim(external_id)) > 0),
  source_url TEXT NOT NULL CHECK (source_url ~ '^https?://'),
  raw_text TEXT NOT NULL,
  published_at TIMESTAMPTZ NOT NULL,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (external_account_id, external_id)
);

CREATE TABLE public.notification_routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_account_id INTEGER NOT NULL REFERENCES public.external_accounts(id) ON DELETE RESTRICT,
  guild_id TEXT NOT NULL REFERENCES public.discord_guilds(guild_id) ON DELETE RESTRICT,
  channel_id TEXT NOT NULL,
  owner_discord_user_id TEXT REFERENCES public.discord_users(discord_user_id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  UNIQUE (external_account_id, channel_id),
  FOREIGN KEY (guild_id, channel_id)
    REFERENCES public.discord_channels(guild_id, channel_id) ON DELETE RESTRICT
);

CREATE TABLE public.notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id BIGINT NOT NULL REFERENCES public.notification_routes(id) ON DELETE RESTRICT,
  source_item_id BIGINT NOT NULL REFERENCES public.source_items(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','sending','retry','sent','failed','unknown','skipped')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ,
  lease_owner TEXT,
  lease_expires_at TIMESTAMPTZ,
  discord_message_id TEXT CHECK (discord_message_id IS NULL OR discord_message_id ~ '^[0-9]+$'),
  last_error TEXT,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  UNIQUE (route_id, source_item_id),
  CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
  CHECK (status <> 'sent' OR (delivered_at IS NOT NULL AND discord_message_id IS NOT NULL))
);

CREATE TABLE public.worker_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type TEXT NOT NULL CHECK (job_type IN ('x_poll','youtube_poll','youtube_collect','spotify_collect','karaoke_collect','lyrics_collect')),
  idempotency_key TEXT NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
  external_account_id INTEGER REFERENCES public.external_accounts(id) ON DELETE RESTRICT,
  video_id INTEGER REFERENCES public.videos(id) ON DELETE RESTRICT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(payload) = 'object'),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','running','retry','succeeded','failed','cancelled')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  next_attempt_at TIMESTAMPTZ,
  lease_owner TEXT,
  lease_expires_at TIMESTAMPTZ,
  last_error TEXT,
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  UNIQUE (job_type, idempotency_key),
  CHECK (attempt_count <= max_attempts),
  CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
  CHECK (status NOT IN ('succeeded','failed','cancelled') OR finished_at IS NOT NULL)
);

CREATE TABLE public.runtime_migration_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id UUID NOT NULL UNIQUE,
  catalog_instance_id UUID NOT NULL REFERENCES public.catalog_instance(id) ON DELETE RESTRICT,
  source_fingerprint TEXT NOT NULL CHECK (source_fingerprint ~ '^[0-9a-f]{64}$'),
  manifest_hash TEXT NOT NULL CHECK (manifest_hash ~ '^[0-9a-f]{64}$'),
  summary JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(summary) = 'object'),
  committed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE public.runtime_legacy_id_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id BIGINT NOT NULL REFERENCES public.runtime_migration_receipts(id) ON DELETE RESTRICT,
  source_table TEXT NOT NULL CHECK (length(btrim(source_table)) > 0),
  legacy_id TEXT NOT NULL CHECK (length(btrim(legacy_id)) > 0),
  target_table TEXT NOT NULL CHECK (target_table IN ('collection_states','source_items','notification_routes','notification_deliveries','worker_jobs')),
  target_id TEXT NOT NULL CHECK (length(btrim(target_id)) > 0),
  selection_reason TEXT NOT NULL CHECK (length(btrim(selection_reason)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (source_table, legacy_id, target_table),
  UNIQUE (receipt_id, source_table, legacy_id, target_table)
);

CREATE INDEX collection_states_due_idx ON public.collection_states (next_poll_at, external_account_id)
  WHERE status IN ('idle','backoff');
CREATE INDEX source_items_published_idx ON public.source_items (external_account_id, published_at DESC, id DESC);
CREATE INDEX notification_routes_active_idx ON public.notification_routes (external_account_id, id)
  WHERE is_active;
CREATE INDEX notification_deliveries_due_idx ON public.notification_deliveries (next_attempt_at, id)
  WHERE status IN ('pending','retry');
CREATE INDEX worker_jobs_due_idx ON public.worker_jobs (next_attempt_at, id)
  WHERE status IN ('pending','retry');
CREATE INDEX runtime_legacy_id_map_target_idx ON public.runtime_legacy_id_map (target_table, target_id);

CREATE TRIGGER discord_users_touch BEFORE UPDATE ON public.discord_users
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_timestamp();
CREATE TRIGGER discord_guilds_touch BEFORE UPDATE ON public.discord_guilds
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_timestamp();
CREATE TRIGGER discord_channels_touch BEFORE UPDATE ON public.discord_channels
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_timestamp();
CREATE TRIGGER collection_states_touch BEFORE UPDATE ON public.collection_states
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_version();
CREATE TRIGGER notification_routes_touch BEFORE UPDATE ON public.notification_routes
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_version();
CREATE TRIGGER notification_deliveries_touch BEFORE UPDATE ON public.notification_deliveries
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_version();
CREATE TRIGGER worker_jobs_touch BEFORE UPDATE ON public.worker_jobs
  FOR EACH ROW EXECUTE FUNCTION public.catalog_touch_version();
CREATE TRIGGER runtime_migration_receipts_immutable BEFORE UPDATE OR DELETE ON public.runtime_migration_receipts
  FOR EACH ROW EXECUTE FUNCTION public.catalog_reject_history_mutation();
CREATE TRIGGER runtime_legacy_id_map_immutable BEFORE UPDATE OR DELETE ON public.runtime_legacy_id_map
  FOR EACH ROW EXECUTE FUNCTION public.catalog_reject_history_mutation();

UPDATE public.catalog_instance SET schema_version='catalog-v2';
