"""Curated artist aliases and lossless catalogue presentation.

Grouping is a read model: registration IDs, owners and source records stay intact.
Never infer identity from a similar name or from a romanization generated by AI.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Any


def name_key(value: str | None) -> str:
    return re.sub(r"[\s_]", "", unicodedata.normalize("NFKC", value or "")).casefold()


def has_kanji(value: str) -> bool:
    return bool(re.search(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]", value))


@lru_cache(maxsize=1)
def identities() -> tuple[dict[str, Any], ...]:
    path = Path(__file__).resolve().parents[1] / 'data' / 'artist_identities.json'
    return tuple(json.loads(path.read_text(encoding='utf-8')))


def identity_for(name: str, display_name: str | None = None, agency: str | None = None) -> dict[str, Any] | None:
    keys = {name_key(name), name_key(display_name)} - {''}
    for identity in identities():
        if agency and name_key(agency) != name_key(identity['agency']):
            continue
        if keys.intersection(name_key(alias) for alias in identity['aliases']):
            return identity
    return None


def display_artist_name(name: str, display_name: str | None = None, agency: str | None = None) -> str:
    identity = identity_for(name, display_name, agency)
    if identity:
        return identity['display_name']
    # Respect explicit bilingual names even for artists outside the curated list.
    value = display_name or name
    if has_kanji(value) and re.fullmatch(r'[A-Za-z][A-Za-z0-9 _.-]*', name) and '(' not in value and '/' not in value:
        return f'{value} ({name.replace("_", " ")})'
    parts = [part.strip() for part in re.split(r'\s*/\s*|[()]', value) if part.strip()]
    if len(parts) == 2:
        native = next((part for part in parts if has_kanji(part)), None)
        latin = next((part for part in parts if re.fullmatch(r'[\x20-\x7e]+', part) and re.search('[A-Za-z]', part)), None)
        if native and latin:
            return f'{native} ({latin})'
    return value


def artist_name_aliases(name: str) -> list[str]:
    identity = identity_for(name)
    return list(dict.fromkeys([name, *(identity['aliases'] if identity else [])]))


def normalize_artist_display_names(conn: Any, *, apply: bool = False) -> list[dict[str, Any]]:
    changes = []
    for row in conn.execute('SELECT id, name, display_name, agency FROM artists ORDER BY id').fetchall():
        label = display_artist_name(row['name'], row['display_name'], row['agency'])
        if label != (row['display_name'] or row['name']):
            changes.append({'id': row['id'], 'before': row['display_name'], 'after': label})
            if apply:
                conn.execute('UPDATE artists SET display_name = %s, updated_at = CURRENT_TIMESTAMP WHERE id = %s', (label, row['id']))
    return changes


def find_preset_artist(conn: Any, owner_id: str, name: str, agency: str | None) -> dict[str, Any] | None:
    """Reuse an exact curated alias without taking over a personal registration."""
    aliases = [name_key(alias) for alias in artist_name_aliases(name)]
    return conn.execute(
        """SELECT id FROM artists
        WHERE (discord_user_id = %s OR (discord_user_id IS NULL AND agency = %s))
          AND (agency IS NULL OR %s::text IS NULL OR agency = %s)
          AND regexp_replace(LOWER(name), '[[:space:]_]', '', 'g') = ANY(%s)
        ORDER BY (discord_user_id = %s) DESC NULLS LAST, id LIMIT 1""",
        (owner_id, agency, agency, agency, aliases, owner_id),
    ).fetchone()


def group_artists(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Combine confirmed aliases for display, retaining every ID and source."""
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        identity = identity_for(row['name'], row.get('display_name'), row.get('agency'))
        key = identity['key'] if identity else f"registration:{row['id']}"
        groups.setdefault(key, []).append(row)
    result = []
    for members in groups.values():
        # Keep an existing Spotify match addressable; otherwise use the oldest ID.
        members = sorted(members, key=lambda row: (not bool(row.get('spotify_artist_id')), row['id']))
        merged = dict(members[0])
        merged['related_artist_ids'] = sorted(row['id'] for row in members)
        merged['name_aliases'] = list(dict.fromkeys(alias for row in members for alias in artist_name_aliases(row['name'])))
        merged['display_name'] = display_artist_name(merged['name'], merged.get('display_name'), merged.get('agency'))
        for field in ('agency', 'profile_intro', 'debut_date', 'spotify_image_url', 'representative_youtube_url', 'notes'):
            merged[field] = next((row.get(field) for row in members if row.get(field)), None)
        for field in ('show_in_spotify', 'show_in_lyrics', 'show_in_youtube_lives'):
            if field in merged:
                merged[field] = any(row.get(field, False) for row in members)
        if 'sources' in merged:
            # Retain source IDs and owning artist IDs, even when handles coincide.
            merged['sources'] = [source for row in members for source in row.get('sources', [])]
        result.append(merged)
    return sorted(result, key=lambda row: name_key(row['display_name']))
